"""Added Product model

Revision ID: 0afd834a7254
Revises: a76cc9df0b5c
Create Date: 2023-09-07 20:04:57.608753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afd834a7254'
down_revision = 'a76cc9df0b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
