"""Added Cart  model

Revision ID: e378de7e0f39
Revises: 0afd834a7254
Create Date: 2023-09-07 20:16:54.015296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e378de7e0f39'
down_revision = '0afd834a7254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
